# =============================================================================
# Classification — annabel_vinc_supcon2_s3v1  |  features: z_recon (latent)
# =============================================================================
root_folder : "/net/projects/CLS/lding/data/fa_data_analysis"

input:
  latents_csv : root_folder + "/ae_results/contrastive_run/annabel_vinc_supcon2_s3v1/latents.csv"

output:
  out_dir : root_folder + "/ae_results/contrastive_run/annabel_vinc_supcon2_s3v1/fa_cls_zrecon"

labels:
  label_col    : "annotation_label_name"
  filename_col : "filename"
  label_order:
    - "No adhesion"
    - "adhesion"

features:
  feature_prefix        : "z_"
  include_mean_intensity: false

split:
  strategy     : "from_csv"

classifier:
  type : "lgbm"

lightgbm:
  n_estimators      : 500
  learning_rate     : 0.05
  num_leaves        : 31
  min_child_samples : 10
  class_weight      : "balanced"
