#!/usr/bin/env bash
# submit_patchprep_ch02.sh — auto-generated by generate_patchprep_ch02.py
# Extracts ch0 and ch2 patches for all datasets (needed by protein sweep)
#
# Total jobs: 16
set -eo pipefail
mkdir -p logs/slurm

PYTHON=/home/liyading/miniconda3/bin/python3
RUNNER=/net/projects/CLS/lding/gitcode/SubCellAE/scripts/run_patchprep_from_config.py

echo "Submitting 16 patchprep jobs (ch0 + ch2)..."

JOB=$(sbatch --parsable \
    --job-name="nih3t3_control_ch0" \
    --partition=general \
    --cpus-per-task=4 \
    --mem=48G \
    --time=12:00:00 \
    --output="logs/slurm/nih3t3_control_ch0_%j.out" \
    --wrap="exec 2>&1
export PYTHONPATH='/net/projects/CLS/lding/gitcode/SubCellAE:/net/projects/CLS/lding/conda_env/core_env/lib/python3.11/site-packages'
echo Node: $(hostname)
echo Start: $(date)
$PYTHON $RUNNER /net/projects/CLS/lding/gitcode/SubCellAE/config/patchprep_ch02_config/nih3t3_control_cio_rb_ch0.yaml
echo End: $(date)")
echo "  nih3t3_control_ch0 -> $JOB"

JOB=$(sbatch --parsable \
    --job-name="nih3t3_control_ch2" \
    --partition=general \
    --cpus-per-task=4 \
    --mem=48G \
    --time=12:00:00 \
    --output="logs/slurm/nih3t3_control_ch2_%j.out" \
    --wrap="exec 2>&1
export PYTHONPATH='/net/projects/CLS/lding/gitcode/SubCellAE:/net/projects/CLS/lding/conda_env/core_env/lib/python3.11/site-packages'
echo Node: $(hostname)
echo Start: $(date)
$PYTHON $RUNNER /net/projects/CLS/lding/gitcode/SubCellAE/config/patchprep_ch02_config/nih3t3_control_cio_rb_ch2.yaml
echo End: $(date)")
echo "  nih3t3_control_ch2 -> $JOB"

JOB=$(sbatch --parsable \
    --job-name="nih3t3_ycomp_ch0" \
    --partition=general \
    --cpus-per-task=4 \
    --mem=48G \
    --time=12:00:00 \
    --output="logs/slurm/nih3t3_ycomp_ch0_%j.out" \
    --wrap="exec 2>&1
export PYTHONPATH='/net/projects/CLS/lding/gitcode/SubCellAE:/net/projects/CLS/lding/conda_env/core_env/lib/python3.11/site-packages'
echo Node: $(hostname)
echo Start: $(date)
$PYTHON $RUNNER /net/projects/CLS/lding/gitcode/SubCellAE/config/patchprep_ch02_config/nih3t3_ycomp_cio_rb_ch0.yaml
echo End: $(date)")
echo "  nih3t3_ycomp_ch0 -> $JOB"

JOB=$(sbatch --parsable \
    --job-name="nih3t3_ycomp_ch2" \
    --partition=general \
    --cpus-per-task=4 \
    --mem=48G \
    --time=12:00:00 \
    --output="logs/slurm/nih3t3_ycomp_ch2_%j.out" \
    --wrap="exec 2>&1
export PYTHONPATH='/net/projects/CLS/lding/gitcode/SubCellAE:/net/projects/CLS/lding/conda_env/core_env/lib/python3.11/site-packages'
echo Node: $(hostname)
echo Start: $(date)
$PYTHON $RUNNER /net/projects/CLS/lding/gitcode/SubCellAE/config/patchprep_ch02_config/nih3t3_ycomp_cio_rb_ch2.yaml
echo End: $(date)")
echo "  nih3t3_ycomp_ch2 -> $JOB"

JOB=$(sbatch --parsable \
    --job-name="pfak_control_ch0" \
    --partition=general \
    --cpus-per-task=4 \
    --mem=48G \
    --time=12:00:00 \
    --output="logs/slurm/pfak_control_ch0_%j.out" \
    --wrap="exec 2>&1
export PYTHONPATH='/net/projects/CLS/lding/gitcode/SubCellAE:/net/projects/CLS/lding/conda_env/core_env/lib/python3.11/site-packages'
echo Node: $(hostname)
echo Start: $(date)
$PYTHON $RUNNER /net/projects/CLS/lding/gitcode/SubCellAE/config/patchprep_ch02_config/pfak_control_cio_rb_ch0.yaml
echo End: $(date)")
echo "  pfak_control_ch0 -> $JOB"

JOB=$(sbatch --parsable \
    --job-name="pfak_control_ch2" \
    --partition=general \
    --cpus-per-task=4 \
    --mem=48G \
    --time=12:00:00 \
    --output="logs/slurm/pfak_control_ch2_%j.out" \
    --wrap="exec 2>&1
export PYTHONPATH='/net/projects/CLS/lding/gitcode/SubCellAE:/net/projects/CLS/lding/conda_env/core_env/lib/python3.11/site-packages'
echo Node: $(hostname)
echo Start: $(date)
$PYTHON $RUNNER /net/projects/CLS/lding/gitcode/SubCellAE/config/patchprep_ch02_config/pfak_control_cio_rb_ch2.yaml
echo End: $(date)")
echo "  pfak_control_ch2 -> $JOB"

JOB=$(sbatch --parsable \
    --job-name="pfak_ycomp_ch0" \
    --partition=general \
    --cpus-per-task=4 \
    --mem=48G \
    --time=12:00:00 \
    --output="logs/slurm/pfak_ycomp_ch0_%j.out" \
    --wrap="exec 2>&1
export PYTHONPATH='/net/projects/CLS/lding/gitcode/SubCellAE:/net/projects/CLS/lding/conda_env/core_env/lib/python3.11/site-packages'
echo Node: $(hostname)
echo Start: $(date)
$PYTHON $RUNNER /net/projects/CLS/lding/gitcode/SubCellAE/config/patchprep_ch02_config/pfak_ycomp_cio_rb_ch0.yaml
echo End: $(date)")
echo "  pfak_ycomp_ch0 -> $JOB"

JOB=$(sbatch --parsable \
    --job-name="pfak_ycomp_ch2" \
    --partition=general \
    --cpus-per-task=4 \
    --mem=48G \
    --time=12:00:00 \
    --output="logs/slurm/pfak_ycomp_ch2_%j.out" \
    --wrap="exec 2>&1
export PYTHONPATH='/net/projects/CLS/lding/gitcode/SubCellAE:/net/projects/CLS/lding/conda_env/core_env/lib/python3.11/site-packages'
echo Node: $(hostname)
echo Start: $(date)
$PYTHON $RUNNER /net/projects/CLS/lding/gitcode/SubCellAE/config/patchprep_ch02_config/pfak_ycomp_cio_rb_ch2.yaml
echo End: $(date)")
echo "  pfak_ycomp_ch2 -> $JOB"

JOB=$(sbatch --parsable \
    --job-name="ppax_control_ch0" \
    --partition=general \
    --cpus-per-task=4 \
    --mem=48G \
    --time=12:00:00 \
    --output="logs/slurm/ppax_control_ch0_%j.out" \
    --wrap="exec 2>&1
export PYTHONPATH='/net/projects/CLS/lding/gitcode/SubCellAE:/net/projects/CLS/lding/conda_env/core_env/lib/python3.11/site-packages'
echo Node: $(hostname)
echo Start: $(date)
$PYTHON $RUNNER /net/projects/CLS/lding/gitcode/SubCellAE/config/patchprep_ch02_config/ppax_control_cio_rb_ch0.yaml
echo End: $(date)")
echo "  ppax_control_ch0 -> $JOB"

JOB=$(sbatch --parsable \
    --job-name="ppax_control_ch2" \
    --partition=general \
    --cpus-per-task=4 \
    --mem=48G \
    --time=12:00:00 \
    --output="logs/slurm/ppax_control_ch2_%j.out" \
    --wrap="exec 2>&1
export PYTHONPATH='/net/projects/CLS/lding/gitcode/SubCellAE:/net/projects/CLS/lding/conda_env/core_env/lib/python3.11/site-packages'
echo Node: $(hostname)
echo Start: $(date)
$PYTHON $RUNNER /net/projects/CLS/lding/gitcode/SubCellAE/config/patchprep_ch02_config/ppax_control_cio_rb_ch2.yaml
echo End: $(date)")
echo "  ppax_control_ch2 -> $JOB"

JOB=$(sbatch --parsable \
    --job-name="ppax_ycomp_ch0" \
    --partition=general \
    --cpus-per-task=4 \
    --mem=48G \
    --time=12:00:00 \
    --output="logs/slurm/ppax_ycomp_ch0_%j.out" \
    --wrap="exec 2>&1
export PYTHONPATH='/net/projects/CLS/lding/gitcode/SubCellAE:/net/projects/CLS/lding/conda_env/core_env/lib/python3.11/site-packages'
echo Node: $(hostname)
echo Start: $(date)
$PYTHON $RUNNER /net/projects/CLS/lding/gitcode/SubCellAE/config/patchprep_ch02_config/ppax_ycomp_cio_rb_ch0.yaml
echo End: $(date)")
echo "  ppax_ycomp_ch0 -> $JOB"

JOB=$(sbatch --parsable \
    --job-name="ppax_ycomp_ch2" \
    --partition=general \
    --cpus-per-task=4 \
    --mem=48G \
    --time=12:00:00 \
    --output="logs/slurm/ppax_ycomp_ch2_%j.out" \
    --wrap="exec 2>&1
export PYTHONPATH='/net/projects/CLS/lding/gitcode/SubCellAE:/net/projects/CLS/lding/conda_env/core_env/lib/python3.11/site-packages'
echo Node: $(hostname)
echo Start: $(date)
$PYTHON $RUNNER /net/projects/CLS/lding/gitcode/SubCellAE/config/patchprep_ch02_config/ppax_ycomp_cio_rb_ch2.yaml
echo End: $(date)")
echo "  ppax_ycomp_ch2 -> $JOB"

JOB=$(sbatch --parsable \
    --job-name="vinc_control_ch0" \
    --partition=general \
    --cpus-per-task=4 \
    --mem=48G \
    --time=12:00:00 \
    --output="logs/slurm/vinc_control_ch0_%j.out" \
    --wrap="exec 2>&1
export PYTHONPATH='/net/projects/CLS/lding/gitcode/SubCellAE:/net/projects/CLS/lding/conda_env/core_env/lib/python3.11/site-packages'
echo Node: $(hostname)
echo Start: $(date)
$PYTHON $RUNNER /net/projects/CLS/lding/gitcode/SubCellAE/config/patchprep_ch02_config/vinc_control_cio_rb_ch0.yaml
echo End: $(date)")
echo "  vinc_control_ch0 -> $JOB"

JOB=$(sbatch --parsable \
    --job-name="vinc_control_ch2" \
    --partition=general \
    --cpus-per-task=4 \
    --mem=48G \
    --time=12:00:00 \
    --output="logs/slurm/vinc_control_ch2_%j.out" \
    --wrap="exec 2>&1
export PYTHONPATH='/net/projects/CLS/lding/gitcode/SubCellAE:/net/projects/CLS/lding/conda_env/core_env/lib/python3.11/site-packages'
echo Node: $(hostname)
echo Start: $(date)
$PYTHON $RUNNER /net/projects/CLS/lding/gitcode/SubCellAE/config/patchprep_ch02_config/vinc_control_cio_rb_ch2.yaml
echo End: $(date)")
echo "  vinc_control_ch2 -> $JOB"

JOB=$(sbatch --parsable \
    --job-name="vinc_ycomp_ch0" \
    --partition=general \
    --cpus-per-task=4 \
    --mem=48G \
    --time=12:00:00 \
    --output="logs/slurm/vinc_ycomp_ch0_%j.out" \
    --wrap="exec 2>&1
export PYTHONPATH='/net/projects/CLS/lding/gitcode/SubCellAE:/net/projects/CLS/lding/conda_env/core_env/lib/python3.11/site-packages'
echo Node: $(hostname)
echo Start: $(date)
$PYTHON $RUNNER /net/projects/CLS/lding/gitcode/SubCellAE/config/patchprep_ch02_config/vinc_ycomp_cio_rb_ch0.yaml
echo End: $(date)")
echo "  vinc_ycomp_ch0 -> $JOB"

JOB=$(sbatch --parsable \
    --job-name="vinc_ycomp_ch2" \
    --partition=general \
    --cpus-per-task=4 \
    --mem=48G \
    --time=12:00:00 \
    --output="logs/slurm/vinc_ycomp_ch2_%j.out" \
    --wrap="exec 2>&1
export PYTHONPATH='/net/projects/CLS/lding/gitcode/SubCellAE:/net/projects/CLS/lding/conda_env/core_env/lib/python3.11/site-packages'
echo Node: $(hostname)
echo Start: $(date)
$PYTHON $RUNNER /net/projects/CLS/lding/gitcode/SubCellAE/config/patchprep_ch02_config/vinc_ycomp_cio_rb_ch2.yaml
echo End: $(date)")
echo "  vinc_ycomp_ch2 -> $JOB"

echo "All patchprep ch02 jobs submitted."
